### ISSUE TITLE
Observable.of(null) triggers addOutputWarning

### ISSUE THREAD

**Issue by Bouncey** [BerkeleyTrue/redux-epic#42]
Returning Observable.of(null) from an epic logs an error to the console. 

```js
invariant(
  Observable.isObservable(result),
    `
      Epics should returned an observable but got %s
      Check the ${name} epic
      `,
      result
  );
```

https://github.com/BerkeleyTrue/redux-epic/blob/master/src/create-epic.js#L102

**Comment by BerkeleyTrue** [comment]
Seems strange that this would trigger the invariant here. Can you provide some sample code that causes the issue?
