### ISSUE TITLE
Basic example code broken

### ISSUE THREAD

**Issue by timjacobi** [BerkeleyTrue/redux-epic#9]
The issue is here

``` JavaScript
.map(user => { type: 'UPDATE_USER', payload: { user: user }})
```

You can't return an object from an arrow function without using return because the curlys will be assumed to relate to the function.

Fix

``` JavaScript
.map(user => { return { type: 'UPDATE_USER', payload: { user: user }}})
```

**Comment by BerkeleyTrue** [comment]
Nice catch! Thanks @timjacobi 

I've corrected the issue. 

Happy Coding

**Comment by timjacobi** [comment]
Here is an even neater fix

``` JavaScript
.map(user => ({ type: 'UPDATE_USER', payload: { user: user }}))
```
